[package]
name = "voxy"
description = "Voxel engine for Bevy"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.14.2"
block-mesh = "0.2.0"
dot_vox = "5.1.1"
futures = "0.3.31"
ndshape = "0.3.0"
smol = "2.0.2"
uuid = "1.10.0"
